class CreateSchoolData < ActiveRecord::Migration
  def change
    create_table :school_data do |t|
      t.references :school, index: true
      t.string :dbn
      t.string :year
      t.string :name
      t.string :grades_served
      t.string :primary_address
      t.string :city
      t.string :zip
      t.string :principal_name
      t.string :phone_number
      t.string :district
      t.string :total_enrollment
      t.string :shared_site
      t.string :year_opened
      t.string :website
      t.string :male
      t.string :female
      t.string :asian
      t.string :black
      t.string :latino
      t.string :white
      t.string :other
      t.string :whith_disabilities
      t.string :free_reduced_price_lunch
      t.string :english_language_learners
      t.string :pre_kinder
      t.string :kinder
      t.string :grade1
      t.string :grade2
      t.string :grade3
      t.string :grade4
      t.string :grade5
      t.string :grade6
      t.string :grade7
      t.string :grade8
      t.string :grade9
      t.string :grade10
      t.string :grade11
      t.string :grade12
      t.string :attendance_es_ms_k8_ec
      t.string :attendance_hs_transfer_hs
      t.string :es_ms_k8_ecpr_s_type
      t.string :es_ms_k8_ec_o_pr_score
      t.string :es_ms_k8_ec_s_pr_grade
      t.string :es_ms_k8_ec_s_prog_score
      t.string :es_ms_k8_ec_s_prog_grade
      t.string :es_ms_k8_ec_s_perf_pr_score
      t.string :es_ms_k8_ec_s_perf_pr_grade
      t.string :es_ms_k8_ec_s_enviro_pr_score
      t.string :es_ms_k8_ec_s_enviro_pr_grade
      t.string :hs_t_hs_o_pr_s_type
      t.string :hs_t_hs_o_pr_score
      t.string :hs_t_hs_o_pr_grade
      t.string :hs_t_hs_spro_pr_score
      t.string :hs_t_hs_spro_pr_grade
      t.string :hs_t_hs_sper_pr_score
      t.string :hs_t_hs_sper_pr_grade
      t.string :hs_t_hs_se_pr_score
      t.string :hs_t_hs_se_pr_grade
      t.string :hs_t_hs_o_cac_score
      t.string :hs_t_hs_o_cac_grade
      t.string :av_proficiency_rating_ela
      t.string :third_a_p_r_ela
      t.string :fourth_a_p_r_ela
      t.string :fifth_a_p_r_ela
      t.string :sixth_a_p_r_ela
      t.string :seventh_a_p_r_ela
      t.string :eigth_a_p_r_ela
      t.string :third_pr_s_level1_ela
      t.string :third_pr_s_level2_ela
      t.string :third_pr_s_level3_ela
      t.string :third_pr_s_level4_ela
      t.string :fourth_pr_s_level1_ela
      t.string :fourth_pr_s_level2_ela
      t.string :fourth_pr_s_level3_ela
      t.string :fourth_pr_s_level4_ela
      t.string :fifth_pr_s_level1_ela
      t.string :fifth_pr_s_level2_ela
      t.string :fifth_pr_s_level3_ela
      t.string :fifth_pr_s_level4_ela
      t.string :sixth_pr_s_level1_ela
      t.string :sixth_pr_s_level2_ela
      t.string :sixth_pr_s_level3_ela
      t.string :sixth_pr_s_level4_ela
      t.string :seventh_pr_s_level1_ela
      t.string :seventh_pr_s_level2_ela
      t.string :seventh_pr_s_level3_ela
      t.string :seventh_pr_s_level4_ela
      t.string :eigth_pr_s_level1_ela
      t.string :eigth_pr_s_level2_ela
      t.string :eigth_pr_s_level3_ela
      t.string :eigth_pr_s_level4_ela
      t.string :all_grades_p_level1_ela
      t.string :all_grades_p_level2_ela
      t.string :all_grades_p_level3_ela
      t.string :all_grades_p_level4_ela
      t.string :av_proficiency_rating_math
      t.string :third_a_p_r_math
      t.string :fourth_a_p_r_math
      t.string :fifth_a_p_r_math
      t.string :sixth_a_p_r_math
      t.string :seventh_a_p_r_math
      t.string :eigth_a_p_r_math
      t.string :third_pr_s_level1_math
      t.string :third_pr_s_level2_math
      t.string :third_pr_s_level3_math
      t.string :third_pr_s_level4_math
      t.string :fourth_pr_s_level1_math
      t.string :fourth_pr_s_level2_math
      t.string :fourth_pr_s_level3_math
      t.string :fourth_pr_s_level4_math
      t.string :fifth_pr_s_level1_math
      t.string :fifth_pr_s_level2_math
      t.string :fifth_pr_s_level3_math
      t.string :fifth_pr_s_level4_math
      t.string :sixth_pr_s_level1_math
      t.string :sixth_pr_s_level2_math
      t.string :sixth_pr_s_level3_math
      t.string :sixth_pr_s_level4_math
      t.string :seventh_pr_s_level1_math
      t.string :seventh_pr_s_level2_math
      t.string :seventh_pr_s_level3_math
      t.string :seventh_pr_s_level4_math
      t.string :eigth_pr_s_level1_math
      t.string :eigth_pr_s_level2_math
      t.string :eigth_pr_s_level3_math
      t.string :eigth_pr_s_level4_math
      t.string :all_grades_p_level1_math
      t.string :all_grades_p_level2_math
      t.string :all_grades_p_level3_math
      t.string :all_grades_p_level4_math
      t.string :sat_n_test_takers
      t.string :sat_a_math_s
      t.string :sat_a_cr_s
      t.string :sat_a_writing_s
      t.string :sat_a_total_s
      t.string :pp_r_english
      t.string :as_r_english
      t.string :pcr_r_comprehensive_english
      t.string :pp_r_us_history
      t.string :as_r_us_history
      t.string :pp_r_global_history
      t.string :as_r_global_history
      t.string :pp_r_living_environment
      t.string :as_r_living_environment
      t.string :pp_r_earth_science
      t.string :as_r_earth_science
      t.string :pp_r_chemistry
      t.string :as_r_chemistry
      t.string :pp_r_physics
      t.string :as_r_physics
      t.string :pp_r_integrated_algebra
      t.string :as_r_integrated_algebra
      t.string :pcr_r_integrated_algebra
      t.string :pp_r_geometry
      t.string :as_r_geometry
      t.string :pcr_r_geometry
      t.string :pp_r_algebraii
      t.string :as_r_algebraii
      t.string :pcr_r_algebraii
      t.string :fourth_year_g_r
      t.string :sixth_year_g_r
      t.string :transfer_s_graduation_r
      t.string :p_s_earning10_credits_in1year
      t.string :fourth_year_non_remediation_rate
      t.string :c_readiness_r_including_p
      t.string :cc_preparatory_course_index
      t.string :postsecondary_enrollment_rate_6months
      t.string :p_total_response_rate
      t.string :p_academic_expectations_rs
      t.string :p_communication_rs
      t.string :p_engagement_rs
      t.string :p_safety_respect_rs
      t.string :t_total_response_rate
      t.string :t_academic_expectations_rs
      t.string :t_communication_rs
      t.string :t_engagement_rs
      t.string :t_safety_respect_rs
      t.string :s_total_response_rate
      t.string :s_academic_expectations_rs
      t.string :s_communication_rs
      t.string :s_engagement_rs
      t.string :s_safety_respect_rs
      t.string :s_q1f_agree
      t.string :s_q1f_strongly_agree
      t.string :s_q2b_agree
      t.string :s_q2b_strongly_agree
      t.string :s_q4e_agree
      t.string :s_q4e_strongly_agree
      t.string :s_q4g_agree
      t.string :s_q4g_strongly_agree
      t.string :s_q6c_agree
      t.string :s_q6c_strongly_agree
      t.string :t_q3d_agree
      t.string :t_q3d_strongly_agree
      t.string :t_q8c_strongly_agree
      t.string :t_q8c_agree
      t.string :t_q10c_agree
      t.string :t_q10c_strongly_agree
      t.string :t_q11e_disagree
      t.string :t_q11e_strongly_disagree
      t.string :t_q11f_strongly_agree
      t.string :t_q11f_agree
      t.string :p_q1a_agree
      t.string :p_q1a_strongly_agree
      t.string :p_q1g_agree
      t.string :p_q1g_strongly_agree
      t.string :p_q2a_agree
      t.string :p_q2a_strongly_agree
      t.string :p_q3a_agree
      t.string :p_q3a_strongly_agree
      t.string :p_q5b_satisfied
      t.string :p_q5b_very_satisfied
      t.string :quality_review_rating
      t.string :ri_11
      t.string :ri_12
      t.string :ri_14
      t.string :ri_34
      t.string :es_ms_k8_ec_overal_pr_pr
      t.string :es_ms_k8_ec_student_progress_pr_score_pr
      t.string :es_ms_k8_ec_student_performance_pr_pr
      t.string :es_ms_k8_ec_scholl_environment_pr_pr
      t.string :hs_t_hs_overall_pr_pr
      t.string :hs_t_hs_student_progress_pr_pr
      t.string :hs_t_hs_student_performance_pr_pr
      t.string :hs_t_hs_school_environment_pr_pr
      t.string :hs_t_hs_college_carrer_pr_pr
      t.string :attendance_es_ms_k8_ec_pr
      t.string :attendance_hs_pr
      t.string :av_proficiency_rating_ela_pr
      t.string :third_a_p_r_ela_pr
      t.string :fourth_a_p_r_ela_pr
      t.string :fifth_a_p_r_ela_pr
      t.string :sixth_a_p_r_ela_pr
      t.string :seventh_a_p_r_ela_pr
      t.string :eigth_a_p_r_ela_pr
      t.string :third_pr_s_level1_ela_pr
      t.string :third_pr_s_level2_ela_pr
      t.string :third_pr_s_level3_ela_pr
      t.string :third_pr_s_level4_ela_pr
      t.string :fourth_pr_s_level1_ela_pr
      t.string :fourth_pr_s_level2_ela_pr
      t.string :fourth_pr_s_level3_ela_pr
      t.string :fourth_pr_s_level4_ela_pr
      t.string :fifth_pr_s_level1_ela_pr
      t.string :fifth_pr_s_level2_ela_pr
      t.string :fifth_pr_s_level3_ela_pr
      t.string :fifth_pr_s_level4_ela_pr
      t.string :sixth_pr_s_level1_ela_pr
      t.string :sixth_pr_s_level2_ela_pr
      t.string :sixth_pr_s_level3_ela_pr
      t.string :sixth_pr_s_level4_ela_pr
      t.string :seventh_pr_s_level1_ela_pr
      t.string :seventh_pr_s_level2_ela_pr
      t.string :seventh_pr_s_level3_ela_pr
      t.string :seventh_pr_s_level4_ela_pr
      t.string :eigth_pr_s_level1_ela_pr
      t.string :eigth_pr_s_level2_ela_pr
      t.string :eigth_pr_s_level3_ela_pr
      t.string :eigth_pr_s_level4_ela_pr
      t.string :all_grades_p_level1_ela_pr
      t.string :all_grades_p_level2_ela_pr
      t.string :all_grades_p_level3_ela_pr
      t.string :all_grades_p_level4_ela_pr
      t.string :av_proficiency_rating_math_pr
      t.string :third_a_p_r_math_pr
      t.string :fourth_a_p_r_math_pr
      t.string :fifth_a_p_r_math_pr
      t.string :sixth_a_p_r_math_pr
      t.string :seventh_a_p_r_math_pr
      t.string :eigth_a_p_r_math_pr
      t.string :third_pr_s_level1_math_pr
      t.string :third_pr_s_level2_math_pr
      t.string :third_pr_s_level3_math_pr
      t.string :third_pr_s_level4_math_pr
      t.string :fourth_pr_s_level1_math_pr
      t.string :fourth_pr_s_level2_math_pr
      t.string :fourth_pr_s_level3_math_pr
      t.string :fourth_pr_s_level4_math_pr
      t.string :fifth_pr_s_level1_math_pr
      t.string :fifth_pr_s_level2_math_pr
      t.string :fifth_pr_s_level3_math_pr
      t.string :fifth_pr_s_level4_math_pr
      t.string :sixth_pr_s_level1_math_pr
      t.string :sixth_pr_s_level2_math_pr
      t.string :sixth_pr_s_level3_math_pr
      t.string :sixth_pr_s_level4_math_pr
      t.string :seventh_pr_s_level1_math_pr
      t.string :seventh_pr_s_level2_math_pr
      t.string :seventh_pr_s_level3_math_pr
      t.string :seventh_pr_s_level4_math_pr
      t.string :eigth_pr_s_level1_math_pr
      t.string :eigth_pr_s_level2_math_pr
      t.string :eigth_pr_s_level3_math_pr
      t.string :eigth_pr_s_level4_math_pr
      t.string :all_grades_p_level1_math_pr
      t.string :all_grades_p_level2_math_pr
      t.string :all_grades_p_level3_math_pr
      t.string :all_grades_p_level4_math_pr
      t.string :sat_n_test_takers_pr
      t.string :sat_a_math_s_pr
      t.string :sat_a_cr_s_pr
      t.string :sat_a_writing_s_pr
      t.string :sat_a_total_s_pr
      t.string :pp_r_english_pr
      t.string :as_r_english_pr
      t.string :pcr_r_comprehensive_english_pr
      t.string :pp_r_us_history_pr
      t.string :as_r_us_history_pr
      t.string :pp_r_global_history_pr
      t.string :as_r_global_history_pr
      t.string :pp_r_living_environment_pr
      t.string :as_r_living_environment_pr
      t.string :pp_r_earth_science_pr
      t.string :as_r_earth_science_pr
      t.string :pp_r_chemistry_pr
      t.string :as_r_chemistry_pr
      t.string :pp_r_physics_pr
      t.string :as_r_physics_pr
      t.string :pp_r_integrated_algebra_pr
      t.string :as_r_integrated_algebra_pr
      t.string :pcr_r_integrated_algebra_pr
      t.string :pp_r_geometry_pr
      t.string :as_r_geometry_pr
      t.string :pcr_r_geometry_pr
      t.string :pp_r_algebraii_pr
      t.string :as_r_algebraii_pr
      t.string :pcr_r_algebraii_pr
      t.string :fourth_year_g_r_pr
      t.string :sixth_year_g_r_pr
      t.string :transfer_s_graduation_r_pr
      t.string :p_s_earning10_credits_in1year_pr
      t.string :fourth_year_non_remediation_rate_pr
      t.string :c_readiness_r_including_p_pr
      t.string :cc_preparatory_course_index_pr
      t.string :postsecondary_enrollment_rate_6months_pr
      t.string :p_total_response_rate_pr
      t.string :p_academic_expectations_rs_pr
      t.string :p_communication_rs_pr
      t.string :p_engagement_rs_pr
      t.string :p_safety_respect_rs_pr
      t.string :t_total_response_rate_pr
      t.string :t_academic_expectations_rs_pr
      t.string :t_communication_rs_pr
      t.string :t_engagement_rs_pr
      t.string :t_safety_respect_rs_pr
      t.string :s_total_response_rate_pr
      t.string :s_academic_expectations_rs_pr
      t.string :s_communication_rs_pr
      t.string :s_engagement_rs_pr
      t.string :s_safety_respect_rs_pr
      t.string :s_q1f_agree_pr
      t.string :s_q1f_strongly_agree_pr
      t.string :s_q2b_agree_pr
      t.string :s_q2b_strongly_agree_pr
      t.string :s_q4e_agree_pr
      t.string :s_q4e_strongly_agree_pr
      t.string :s_q4g_agree_pr
      t.string :s_q4g_strongly_agree_pr
      t.string :s_q6c_agree_pr
      t.string :s_q6c_strongly_agree_pr
      t.string :t_q3d_agree_pr
      t.string :t_q3d_strongly_agree_pr
      t.string :t_q8c_strongly_agree_pr
      t.string :t_q8c_agree_pr
      t.string :t_q10c_agree_pr
      t.string :t_q10c_strongly_agree_pr
      t.string :t_q11e_disagree_pr
      t.string :t_q11e_strongly_disagree_pr
      t.string :t_q11f_strongly_agree_pr
      t.string :t_q11f_agree_pr
      t.string :p_q1a_agree_pr
      t.string :p_q1a_strongly_agree_pr
      t.string :p_q1g_agree_pr
      t.string :p_q1g_strongly_agree_pr
      t.string :p_q2a_agree_pr
      t.string :p_q2a_strongly_agree_pr
      t.string :p_q3a_agree_pr

      t.timestamps
    end
  end
end
